### ISSUE TITLE
Delegate slots not rendering in rspec tests

### ISSUE THREAD

**Issue by molenick-mov** [github/view_component#859] opened 2021-04-14 21:36 UTC
I have a component with a delegate slot that works as expected on an actual page, but is failing to render the delegate slot's content in an RSpec test.  I had trouble finding information on testing View Components with RSpec, so it's very possible I've gotten something wrong.

Components:
```
class BlogComponent < ViewComponent::Base
  attr_reader :blog
  renders_one :author, AuthorComponent

  def initialize(blog:)
    @blog = blog
  end
end

class AuthorComponent < ViewComponent::Base
  attr_reader :author, 

  def initialize(author:)
    @author = author
  end
end
```

show.html.erb:
```
<%= render BlogComponent.new(blog: blog) do |c| %>
  <% c.author(author: @blog.author) %>
<% end %>
```

blog_component.html.erb:
```
<section>
  <%= author %>
</section>
```

author_component.html.erb:
```
<section>
  Author: <%= author.name %>
</section>
```

Blog Component rspec test:
```
require 'rails_helper'

RSpec.describe BlogComponent, type: :component do
  subject(:component) { described_class.new(blog: blog) }
  let!(:blog) { FactoryBot.create(:blog, author: author) }\
  let(:author) { FactoryBot.create(:author, name: 'Me Person') }

  it 'displays the author' do
    expect(Capybara.string(render_inline(component { |c| c.author(author: blog.author) }))).to have_text('Me Person')
  end
end
```

When I render the blog component, I expect the rendered output to be:
```
<section>
  <section>
    Me Person
  </section>
</section>
```

But instead what renders is:
```
<section>
  <section>
 
  </section>
</section>
```

Gem version: view_component (2.30.0)
Rails version: 5.2.5
Ruby version: 2.6.6

**Comment by BlakeWilliams** [comment] 2021-04-15 13:45
I think this may be a bug in your test.

Here's your test broken up and syntax highlighted so it's a bit easier to read/understand:

```ruby
  result = render_inline(component { |c| c.author(author: blog.author) })
  page = Capybara.string(result)

  expect(page).to have_text('Me Person')
```

I think the issue is that you're passing the block to `component` and not `render_inline`. Can you try the following?

```ruby
  result = render_inline(component) { |c| c.author(author: blog.author) }
  page = Capybara.string(result)

  expect(page).to have_text('Me Person')
```

I'm closing this for now, but if the above doesn't fix it feel free to re-open the issue.

**Closed by BlakeWilliams** 2021-04-15 13:45 UTC

**Comment by BlakeWilliams** [comment] 2021-04-15 13:50
Related, @palkan just contributed some updates to our RSpec documentation here: https://viewcomponent.org/guide/testing.html#rspec-configuration

Hope that helps!

**Comment by molenick-mov** [comment] 2021-04-15 16:38
Thanks!  I'll give that a whirl and read the new documentation.
