### ISSUE TITLE
Instrumentation (ActiveSupport notifications)

### ISSUE THREAD

**Issue by palkan** [github/view_component#893] opened 2021-04-30 12:13 UTC
## Feature request

Add ActiveSupport notifications support (`render.view_component`?).

### Motivation

Instrumentation could be useful for different reasons:
- Measuring rendering performance (APM-like stuff)
- Performing runtime analysis: e.g., detect unused components, build component dependency trees (could be used for caching).

Since ViewComponent aims to be as performant as possible, this feature could be opt-in (e.g., `ActiveSupport.on_load(:view_component) { include ViewComponent::Instrumentation }` or whatever).

**Comment by joelhawksley** [comment] 2021-05-04 13:58
@palkan sure! Would you like to take this on?

**Comment by palkan** [comment] 2021-05-04 14:52
Sure. Any deadlines?)

**Comment by joelhawksley** [comment] 2021-05-04 20:01
@palkan no rush at all!

**Comment by baxang** [comment] 2021-05-28 05:57
Just to help people to navigate, this seems like a duplicate of https://github.com/github/view_component/issues/427

**Closed** 2021-06-08 14:10 UTC
Labels: help wanted
